# Generated by Django 3.2.18 on 2023-05-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0008_auto_20190606_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='extra_permission',
            field=models.CharField(db_index=True, default='', max_length=250, null=True),
        ),
    ]
