# Generated by Django 3.2.18 on 2023-05-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_auto_20200615_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='scope',
            field=models.TextField(choices=[('normal', 'Normal'), ('testing', 'Test Server'), ('security', 'Security')], default='normal', verbose_name='scope'),
        ),
    ]
